replicaCount: 2

image:
  repository: 587452804817.dkr.ecr.us-east-1.amazonaws.com/flask-ci-cd
  pullPolicy: IfNotPresent
  tag: "latest" 

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5001

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: []

serviceAccount:
  create: true
  name: ""
