name: Continuous Integration

on:
  push: 
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/jobs/test.yml

  build-push:
    needs: test
    uses: ./.github/workflows/jobs/build_push.yml
    secrets: inherit

  cleanup:
    needs: build-push
    uses: ./.github/workflows/jobs/cleanup.yml
    secrets: inherit